resolver: lts-12.1

extra-deps:
  - 'heist-1.1'
  - 'map-syntax-0.3'
  - "xmlhtml-0.2.5.2"

packages:
  - digestive-functors/
  - digestive-functors-blaze/
  - digestive-functors-happstack/
  - digestive-functors-heist/
  - digestive-functors-snap/
